server:
 port: 8086
 contextPath: /

spring:
  #profiles:
   # active: dev
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
  h2:
     console:
        enabled: true