server:
 port: 8086
 contextPath: /

spring:
  #profiles:
   # active: dev
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
  h2:
     console:
        enabled: true

rest:
 url: http://localhost:8085/products
 token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk2OTc5MDYsInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiYmE2MGUxZGYtMmYxOC00MTYxLWE0NjYtZmRkOGZkYTAxMDg1IiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.wOC8Fq995W3lb1dv81fTl5VF78qpSifuRRKIJvBZqiTcq1wSx36bWCQfibXmYzNm0NQ2CAtbUoTOkB2oNOiOKgXS9IoImhpkHWxOEigffYHMfGtNeGt1AoCivm3ijp7pCzE3bFymtII2ZTRmZ3Qq3ft_ENl8wJedB9brVcAnx7mMy6ysvVz5xlMt7yRSK97skqN2BJiKf74YVQxjh9afkaXyEKXs7rbwzh472I1_3aIT3ehxqzuRDpOwkEztH9_cflEqZQZu12Yqdb0Ji_wT1fpowe5Rsd69kb4r1Qc6HP9e2xFomlUsL2Srwvcx-iJHCu--QHEy20VRiFXWpj4ktA