
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
  h2:
     console:
        enabled: true

rest:
 url: http://localhost:8085/products
 token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk3MDM1MzksInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNWVmODI2YmItOTM5My00NTc1LWEzODctYzcyMTRkYzY0Nzk1IiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.lgHgA_hsFu3FSAUCUY-JvY_CZRCRpKYPInyGz5iKaV_w0vt3FYHO3pEyeXqHTsUClduNniCU9binOjtsWkAHr9X4M-sVN8BcXy9iMAYnWP0b0-YEI9tbqod_SrxbsenPW2uA3AMWsBp47QjBip-GGvJyJRENzZPtm_Eg4jDbEt94Az2gBePgygNcM1hPwi2gzzb9i8c7NH1-Y-C3Us_UA1pBZe8ONbZIO0oTG2dgPBD6WCgKSuSe1x7KNW-w37KhqCy-bRlq58kRay9OcJ6H13U2FsfTQ2ESFt7MN63spQfYTKr4oKHtIS1sNzxt4MJhgmhKZ3N4tS6bYlla_oRIKQ

---
spring:
 profiles: dev

 datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
 jpa:
     database-platform: org.hibernate.dialect.H2Dialect
 h2:
     console:
        enabled: true

rest:
 url: http://localhost:8888/dev/products
 token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk3MDM1MzksInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNWVmODI2YmItOTM5My00NTc1LWEzODctYzcyMTRkYzY0Nzk1IiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.lgHgA_hsFu3FSAUCUY-JvY_CZRCRpKYPInyGz5iKaV_w0vt3FYHO3pEyeXqHTsUClduNniCU9binOjtsWkAHr9X4M-sVN8BcXy9iMAYnWP0b0-YEI9tbqod_SrxbsenPW2uA3AMWsBp47QjBip-GGvJyJRENzZPtm_Eg4jDbEt94Az2gBePgygNcM1hPwi2gzzb9i8c7NH1-Y-C3Us_UA1pBZe8ONbZIO0oTG2dgPBD6WCgKSuSe1x7KNW-w37KhqCy-bRlq58kRay9OcJ6H13U2FsfTQ2ESFt7MN63spQfYTKr4oKHtIS1sNzxt4MJhgmhKZ3N4tS6bYlla_oRIKQ


server:
 port: 8085
 servlet:
   context-path: /dev



---
spring:
 profiles: prod

 datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
 jpa:
     database-platform: org.hibernate.dialect.H2Dialect
 h2:
     console:
        enabled: true

rest:
 url: http://localhost:8085/products
 token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDk3MDM1MzksInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNWVmODI2YmItOTM5My00NTc1LWEzODctYzcyMTRkYzY0Nzk1IiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.lgHgA_hsFu3FSAUCUY-JvY_CZRCRpKYPInyGz5iKaV_w0vt3FYHO3pEyeXqHTsUClduNniCU9binOjtsWkAHr9X4M-sVN8BcXy9iMAYnWP0b0-YEI9tbqod_SrxbsenPW2uA3AMWsBp47QjBip-GGvJyJRENzZPtm_Eg4jDbEt94Az2gBePgygNcM1hPwi2gzzb9i8c7NH1-Y-C3Us_UA1pBZe8ONbZIO0oTG2dgPBD6WCgKSuSe1x7KNW-w37KhqCy-bRlq58kRay9OcJ6H13U2FsfTQ2ESFt7MN63spQfYTKr4oKHtIS1sNzxt4MJhgmhKZ3N4tS6bYlla_oRIKQ


server:
 port: 8086
 servlet:
   context-path: /