
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
  h2:
     console:
        enabled: true

rest:
 url: http://localhost:8085/products
 token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTAyMDc2MDYsInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNDRjMWEyZTItYWQ2OS00MWEyLTlkMDUtZGU0NTk2YWNmYzU0IiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.S_yWFytEuIgQL3vP6OuSpPuvsT40eZONTQ-w9V9fKVvQyleURyC5PiquAvI-fegiPeleN2X0SpVWCnv9mm8S1BwZ-1sj8mRYEdzwNpBq87Q6W102WQY3VpqC9WzclUDRp5yR59kuygUrqFeJfibQEmqvvXg5d1rQDIZeVzYqo4GZiTmXCyCv4jhYWkgwAMtDnf0eFGQO-FXEQBDumWEa65tH2kyhgIazWZ_My0a8GsOCQ4erg8JqwbDy0K_gbRyXGh1WtCQvNEY8r5gpV23w5eFeHMuBAbmaiXCxZtSJnaY26fdaD8A1Lp52-2oFZlCp4MnEbmPn2hgNzMoaUwjogA

---
spring:
 profiles: dev

 datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
 jpa:
     database-platform: org.hibernate.dialect.H2Dialect
 h2:
     console:
        enabled: true

rest:
 url: http://localhost:8888/dev/products
 token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTAyMDc2MDYsInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNDRjMWEyZTItYWQ2OS00MWEyLTlkMDUtZGU0NTk2YWNmYzU0IiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.S_yWFytEuIgQL3vP6OuSpPuvsT40eZONTQ-w9V9fKVvQyleURyC5PiquAvI-fegiPeleN2X0SpVWCnv9mm8S1BwZ-1sj8mRYEdzwNpBq87Q6W102WQY3VpqC9WzclUDRp5yR59kuygUrqFeJfibQEmqvvXg5d1rQDIZeVzYqo4GZiTmXCyCv4jhYWkgwAMtDnf0eFGQO-FXEQBDumWEa65tH2kyhgIazWZ_My0a8GsOCQ4erg8JqwbDy0K_gbRyXGh1WtCQvNEY8r5gpV23w5eFeHMuBAbmaiXCxZtSJnaY26fdaD8A1Lp52-2oFZlCp4MnEbmPn2hgNzMoaUwjogA

server:
 port: 8085
 servlet:
   context-path: /dev



---
spring:
 profiles: prod

 datasource:
    url: jdbc:h2:mem:orderdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  
 jpa:
     database-platform: org.hibernate.dialect.H2Dialect
 h2:
     console:
        enabled: true

rest:
 url: http://localhost:8085/products
 token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MTAyMDc2MDYsInVzZXJfbmFtZSI6ImthbmRhbiIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiNDRjMWEyZTItYWQ2OS00MWEyLTlkMDUtZGU0NTk2YWNmYzU0IiwiY2xpZW50X2lkIjoiY2xpZW50aWQiLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiXX0.S_yWFytEuIgQL3vP6OuSpPuvsT40eZONTQ-w9V9fKVvQyleURyC5PiquAvI-fegiPeleN2X0SpVWCnv9mm8S1BwZ-1sj8mRYEdzwNpBq87Q6W102WQY3VpqC9WzclUDRp5yR59kuygUrqFeJfibQEmqvvXg5d1rQDIZeVzYqo4GZiTmXCyCv4jhYWkgwAMtDnf0eFGQO-FXEQBDumWEa65tH2kyhgIazWZ_My0a8GsOCQ4erg8JqwbDy0K_gbRyXGh1WtCQvNEY8r5gpV23w5eFeHMuBAbmaiXCxZtSJnaY26fdaD8A1Lp52-2oFZlCp4MnEbmPn2hgNzMoaUwjogA


server:
 port: 8086
 servlet:
   context-path: /